### Start the tasks
GET http://localhost:7071/api/orchestrators/MasterOrchestrator HTTP/1.1

### Status of the tasks
GET http://localhost:7071/runtime/webhooks/durabletask/instances/2b11cf000b8547e4a0a54012f130571b?taskHub=TestHubName&connection=Storage&code=lOyNvp5nMNnTB_Nbn8PpGPsbHzKFAPWsLS_0fm6ru0yjAzFutdJRNQ== HTTP/1.1